### ISSUE TITLE
Choose either proptypes or flow?  

### ISSUE THREAD

**Issue by simonbengtsson** [agiletechvn/ReactNativeStarterKits#4]
Currently both flow and proptypes are used in the project. As far as I understand there is little to be gained from including both?

https://medium.com/netscape/react-proptypes-to-flow-codemod-9757f5ec5381
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html

**Comment by anhtuank7c** [comment]
We use **React 16**, I use React 15 is no longer.

**Comment by simonbengtsson** [comment]
Yes, but they put proptypes in its own module instead of including it in react 16 because they use [flow](https://flow.org) instead right? It doesn't make sense to use both the proptypes module and flow?

> You may also consider using Flow [instead of proptypes] to statically type check your JavaScript code, including React components.

https://reactjs.org/blog/2017/04/07/react-v15.5.0.html 

There are even [tools](https://github.com/billyvg/codemod-proptypes-to-flow) that converts proptypes to flow syntax as explained here:
https://medium.com/netscape/react-proptypes-to-flow-codemod-9757f5ec5381

**Comment by anhtuank7c** [comment]
I decided to remove **flow**.
I prefer **eslint** and **proptypes**

What is your point?

**Comment by simonbengtsson** [comment]
Got it! You are about to remove the `.flowconfig` and `flow-bin` dependency etc? Would you accept a pull request removing these?

**Comment by anhtuank7c** [comment]
No need PR, i will push new version.
Thank you

**Comment by simonbengtsson** [comment]
Cool. Just because I'm curious. Why do you prefer proptypes over flow?
